### PR TITLE
has-transformed-position

### PR DESCRIPTION
**Pull request by ddkohler**
Using new trait `has-transformed-position` so implement a reference position for newport motors.

Resolves Issue #2 .

### CODE REVIEW

**Comment by ksunden** [comment]
CI error is just that we are using a trait that is not defined in released yaq-traits

**Comment by ddkohler** [comment]
Note to self: update pyproject.toml with before merging.

**Comment by ksunden** [comment]
I would run `pre-commit autoupdate` now that the new version of yaq-traits is out, that should clear up ci stuff

**Comment by ddkohler** [comment]
pre-commit issue is because of old links (my bad, see #7 )

**Pull request merged**
